### PR TITLE
Update Emoji Dictionary

### PR DESCRIPTION
**Pull request by kelvindules**

### CODE REVIEW

**Comment by MihaZupan** [comment]
CI is failing because
```
ok_woman
guardsman
man_with_turban
egg
baseball
```
are duplicates

**Comment by kelvindules** [comment]
Thank you @MihaZupan ! 😄 Just removed those.

**Comment by xoofx** [comment]
Thanks!

**Comment by kelvindules** [comment]
@xoofx Do you plan on updating the nuget any time soon?

**Comment by xoofx** [comment]
Pretty busy on a business trip, ping me back next week

**Comment by kelvindules** [comment]
@xoofx shazam! ⚡️

**Pull request merged**
