### PR TITLE
Fix abbreviation matching

### PR DESCRIPTION
**Pull request by joannaz**
There was an issue with abbreviations matching on a section of a word. For example: PR was matching on PRAA.

### CODE REVIEW

**Comment by xoofx** [comment]
Seems some tests are failing...

**Comment by joannaz** [comment]
Sorry! I have fixed them now.

**Comment by xoofx** [comment]
Thanks! btw, could you add the relevant tests to [AbbreviationSpecs.md](https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/AbbreviationSpecs.md) (you have to regenerate the tests by saving the `Specs.tt` t4 file) for the problem you had in the first place so that we can catch any regressions/behavior on that?

**Comment by joannaz** [comment]
Alright, just pushed the tests up- thanks a bunch!

**Pull request merged**
