### PR TITLE
Added EnableHtmlForBlock flag on HtmlRenderer for issue #104

### PR DESCRIPTION
**Pull request by peinearydevelopment**
#104 I would really like to see this feature as well. From my understanding of your comments, these changes are what is necessary to enable it. Please accept this contribution to enable the feature or let me know what else needs to get done to enable it.

Thanks for creating such a great/useful library!!!

### CODE REVIEW

**Comment by xoofx** [comment]
Hi, unfortunately, I can't accept this PR. Changing the behavior of the Html renderer to not render Html at all is not a good direction (note that the `EnableHtmlForInline` was introduced to support a required feature of rendering nodes without decoration inside links)

The reason is that in order to support #104, I would much prefer that we do this work as part of #32, as it covers broader use cases.

**Comment by peinearydevelopment** [comment]
Thanks for the feedback. That is a little disappointing though as this is for a project I'm currently in the middle of. Please let me know if there is something else I can do to help with this!

**Comment by xoofx** [comment]
> That is a little disappointing 

As I said above, making this as part of the html renderer might not be the worse solution after all.  😉  I just need a bit of time to take a look at the details...

**Comment by xoofx** [comment]
Thanks, I have merged these changes to master

**Comment by peinearydevelopment** [comment]
Thank you for all of your hard work on this library. It is greatly appreciated!!!

**Pull request merged**
