### PR TITLE
fix yaml frontmatter issue when ending with a empty line

### PR DESCRIPTION
**Pull request by yishengjin1413**
@xoofx Please see the test case. We got another issue after fix [issue160](https://github.com/lunet-io/markdig/issues/160).

### CODE REVIEW

**Comment by xoofx** [comment]
Good catch, thanks

**Comment by yishengjin1413** [comment]
@xoofx When do you plan to update the package with this fix?

**Comment by xoofx** [comment]
Just bump the version, should come soon. I don't always push on each PR, so let me know if you are waiting for an update. 😉

**Comment by yishengjin1413** [comment]
Thanks for you so quick response.

**Pull request merged**
