### PR TITLE
Make MediaLinkExtension XML well-formed

### PR DESCRIPTION
**Pull request by FranklinWhale**
Change `<video controls>` to `<video controls="">` and `<iframe allowfullscreen>` to `<iframe allowfullscreen="">`

### CODE REVIEW

**Comment by xoofx** [comment]
Hm, allowfullscreen should be well formed for HTML5 at least. Do you expect to target something else?

**Comment by FranklinWhale** [comment]
It is valid HTML 5, but it is not valid XHTML 5 because of the omission of the attribute value assignment part, making the syntax not XML well-formed. Adding back the value assignment makes it valid for both HTML and XHTML.

https://www.w3.org/TR/html/infrastructure.html#boolean-attribute

**Comment by FranklinWhale** [comment]
Also, if the content is well formed XML, it can processed easily using the LINQ to XML API.

**Comment by FranklinWhale** [comment]
Closing this in favour of #281

**Pull request closed without merging**
