### PR TITLE
Add code coverage

### LINKED ISSUE #351: Code coverage
@xoofx Would you be okay with adding test code coverage to the repo?

I've tested the CI integration on [my fork](https://github.com/MihaZupan/markdig/commit/7d21f8b00356a2a2ccdf9427f6cf4522f4ce9463), exact platform doesn't really matter (currently coveralls).

It could be useful for locating untested sections / branches.

### PR DESCRIPTION
**Pull request by MihaZupan**
Resolves #351 

https://github.com/lunet-io/markdig/commit/e6dd2cf3d4b3d3f723f247843e178dbda8cdd416 simply removes some preprocessor directives as all build targets now support unsafe and fixed strings.

### CODE REVIEW

**Comment by xoofx** [comment]
I'm going to update the appveyor to perform the upload to coveralls

**Comment by xoofx** [comment]
Thanks!

**Comment by xoofx** [comment]
I have added the badge and it now uploads to [markdig results coverall.io](https://coveralls.io/github/lunet-io/markdig?branch=master)
I was not expecting the code to be at 95%... it's a good surprise!

**Comment by MihaZupan** [comment]
And a big chunk of those 5 is not having the prefix tree tests here. Markdig tests are great.

**Pull request merged**
