### PR TITLE
Adding a failing unit test to TestPlainText test class.

### PR DESCRIPTION
**Pull request by hemantkd**
@xoofx Could you confirm if it's a valid test, please?

### CODE REVIEW

**Comment by xoofx** [comment]
It is failing on appveyor. Don't remember the details of PlainText, but not sure by default it keeps the \n in a paragraph (it requires an option that has not been developed likely)

**Comment by xoofx** [comment]
But not sure to understand, you had this test failing on your machine as well right?

**Comment by hemantkd** [comment]
Yes, it is failing on my machine too.

By writing this test, I wanted to highlight the bug. Once we agree that the expected text in the test is correct then we can discuss about a solution.

When the line slice is empty it is ignored when rendering plain text.

For a List block, a new line is put always before rendering.

I can highlight different scenarios with different tests and work in a TDD fashion but might need some help in understanding the requirements.

**Comment by hemantkd** [comment]
Hi @xoofx,

So, do you think the test is invalid?

**Comment by xoofx** [comment]
No, just closing until there is a PR for the whole problem. Can't merge a test alone that is failing ;)
If you try to fix this, be careful that CommonMark doesn't require newlines and you can break a paragraph with new lines without any problem. That's GitHub that is handling this differently here (and there is an extension in Markdig to do the same). So per se, it is not a bug, but it will require a kind of "extension" system for plaintext.

**Comment by hemantkd** [comment]
Cool, Thanks!

**Pull request closed without merging**
