### PR TITLE
Add Normalization Support for AutoLinks

### PR DESCRIPTION
**Pull request by tthiery**
Part of #155 

Question here: Are we normalizing auto links to the InlineLink representation OR back to their original form.

If we want to go back to the original form, we need to extend the syntax (IMHO)

I am for normalizing to InlineLinks.

### CODE REVIEW

**Comment by xoofx** [comment]
> Question here: Are we normalizing auto links to the InlineLink representation OR back to their original form.
> If we want to go back to the original form, we need to extend the syntax (IMHO)

We should support both (via options). if the link doesn't contain this information, we have to add it so that we can recover from.

**Comment by tthiery** [comment]
I added a `InlineLink.IsAutoLink` flag to the syntax and added a `NormalizeOptions.ExpandAutoLinks` option.

The `NormalizeAutoLinkRenderer` has a customized Accept method checking these two flags and execute if applicable.

Set the default for the option to true (meaning it will expand to the "default" InlineLink representation).

Ready for Review

**Comment by xoofx** [comment]
Thanks, will give a look next week!

**Comment by xoofx** [comment]
Thanks

**Pull request merged**
