### PR TITLE
fix emoji performance issue when multiple pipeline needed

### PR DESCRIPTION
**Pull request by yishengjin1413**
We meet a performance issue when we need to use multiple pipeline. After checking the profiling file and have some local test, I find EmojiParser.Initialize is the problem. At the meantime, we don't need to build the PrefixTree for each instance. 

This PR have no logic change, just move the logic to the static constructor.

### CODE REVIEW

**Comment by MihaZupan** [comment]
Did you profile the master branch or the NuGet release? The emoji parser has been updated in between

**Comment by yishengjin1413** [comment]
@MihaZupan  I saw your changes:) Actually, I profiled the release version. But I also run with the master branch, there is not too much improve in my case. We have lots of pipelines need to build and the Initialize will be invoked lots of times. That's the problem.

**Comment by MihaZupan** [comment]
That's odd, there should be a noticeable difference if the emoji init was bottleneck.

**Comment by MihaZupan** [comment]
> This PR have no logic change, just move the logic to the static constructor.

This change removes the option to add custom emojis per instance and currently ignores the instance dictionaries all together.

Those should at least be removed if really not necessary as they are currently misleading.

**Comment by yishengjin1413** [comment]
From the code, I thought your most improvement should be in Match function, right? I checked my test contents and there are not too much emoji actually.

**Comment by xoofx** [comment]
> Those should at least be removed if really not necessary as they are currently misleading.

Sorry, missed that, indeed they should be removed.

**Comment by yishengjin1413** [comment]
@MihaZupan @xoofx  I've remove the two Lazy init in next PR.

**Comment by yishengjin1413** [comment]
@MihaZupan Thanks for let me know. Sounds great and I would like to have another try to profile the master branch. May be I missed something. But this PR change indeed saved lots of time for us.

**Comment by yishengjin1413** [comment]
@MihaZupan I have to say you did a really good job. 👍🏻 I tried in my local with just your changes and the init is not a big problem then. I just stop our tool last time when the running time is longer than my expectation, but actually your changes did work. So this PR become a nice to have now.

**Comment by xoofx** [comment]
oops, ok, sorry to follow this too quickly... so we should revert your both changes @yishengjin1413  or?

**Comment by yishengjin1413** [comment]
@xoofx @MihaZupan  Really thanks for following up with this PR. From my side this PR is still an improvement for us since we really don't need to init it for each instance, but it's not a block issue for us now. Do you think allow the user to customize the emoji is required? Or maybe he can contribute the dictionary here and then we can all use the new emoji? Anyway, I can revert these two PRs if you don't like these. Just let me know.

@xoofx BTW, do you have any plan when you will release a new version? We need a new release to solve the performance issue.

**Comment by MihaZupan** [comment]
No allocations is better than few allocations.
I'd guess that using custom emojis is not common, so we could always add a "CustomEmojiParser" later.

**Comment by xoofx** [comment]
> @xoofx BTW, do you have any plan when you will release a new version? We need a new release to solve the performance issue.

If you are both ok with the changes, I will do it today

**Comment by yishengjin1413** [comment]
@xoofx  Really thanks for your help~ 😉

**Comment by MihaZupan** [comment]
I'll submit a PR to reduce memory allocations of the prefix tree by another ~40% and improve build times today.

**Comment by xoofx** [comment]
ok, I will push a new version right after, thanks @MihaZupan for all your hard work on this! 👍

**Pull request merged**
