### PR TITLE
Expose IndentCount of FencedCodeBlock

### PR DESCRIPTION
**Pull request by 928PJY**
Implement #463

### CODE REVIEW

**Comment by 928PJY** [comment]
@MihaZupan Can you help to review and merge this PR, and will appreciate it if you can tell the ETA of next release.

**Comment by xoofx** [comment]
I'm on holidays and won't be able to look/merge this PR until next week

**Comment by 928PJY** [comment]
Thanks @xoofx . When can I expect an NuGet update, or is there a pre-release NuGet feed with the latest changes?

**Comment by xoofx** [comment]
> Thanks @xoofx . When can I expect an NuGet update, or is there a pre-release NuGet feed with the latest changes?

It should be available in `0.21.1`

**Comment by 928PJY** [comment]
Awesome!

**Pull request merged**
